### ISSUE TITLE
Thumbs subscription keeps unsubscribing in prod environment

### ISSUE THREAD

**Issue by CaseyDStein** [Urigo/meteor-angular-socially#134]
So I created a Meteor app that has an image upload feature based heavily on the image upload functionality in the Socially tutorial.  When I run it locally on localhost:3000 it runs great, images get uploaded, and the thumbs collection gets populated correctly.

However, when I deploy my app to the production environment, the "thumbs" subscription keeps getting unsubscribed and uploaded files never get copied into it.  So my "images" collection has all the images, but the "thumbs" collection is completely empty.  Using the Meteor dev tools for Chrome I can see the following messages sent over DDP:

subscribing to thumbs with PEAbhgKe7eukJoj7y "{"msg":"sub","id":"zYjmkFEHB68QpvZQQ ... } 
unsubscribing from thumbs "{"msg":"unsub","id":"PiZzG2W8uafKbsKta"}" 
subscription ready for thumbs "{"msg":"ready","subs":["zYjmkFEHB68Q ... } 
unsubscribed from thumbs "{"msg":"nosub","id":"PiZzG2W8uafKbsKta"}"

I would appreciate any help you all could provide.

Casey

**Comment by DAB0mB** [comment]
@CaseyDStein Please re-open the issue in [angular-meteor's issues page](https://github.com/Urigo/angular-meteor/issues), because this is not a Socially issue it is a potential issue with the subscription system, maybe of `angular-meteor`. Make sure to provide more details, what is this "thumbs" collection your'e talking about, send a link to your repo or another repo which reproduces the issue. We will be glad to help you :-)
