### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by jjaracz** [Urigo/meteor-angular-socially#140]
Hey,

When I try to run the code from your repository I get this errors.
http://pastebin.com/hgTJYZ2f

I am doing such steps:
`npm install`
`meteor npm install`
`meteor`

**Comment by DAB0mB** [comment]
@jjaracz Thank you for submitting this issue. Part 23 of this tutorial teaches you how to migrate your app, which means it is partially implemented because its true purpose is to give you the right tools to do so, hence the part TypeScript definitions was omitted. The errors you're receiving are actually just warnings logged by the TypeScript compiler, and basically they tell you that the definitions for the angular module were not found. Definitions can be installed through a package manager called "typings". More information about the typings package manager can be found [here](https://github.com/typings/typings).

**Comment by DAB0mB** [comment]
On a second thought I will update the tutorial as well to prevent more misunderstandings similar to yours, and then I will close it. Hopefully I helped you :-)

**Comment by Urigo** [comment]
@DAB0mB that's good to add this to the tutorial but I think what's needed here is to specify running instructions when someone simply clone this repo in the main repo's README - https://github.com/Urigo/meteor-angular-socially/blob/master/README.md

**Comment by DAB0mB** [comment]
@Urigo I shall add some instructions to `README.md` as well.
