### ISSUE TITLE
package isolation failed

### ISSUE THREAD

**Issue by alecperkey** [Urigo/meteor-angular-socially#78]
Hi

I attempted to follow the new step 21 (http://angular-meteor.com/tutorials/angular1/mobile-support-and-packages-isolation) to make a package 'material-accounts', but could not get it to work. 

You can see my fork here: https://github.com/alecperkey/meteor-angular-socially

Also, I got the errors shown here: http://i.imgur.com/sRQxA2j.png

I did mostly everything the same, I think... but apparently not. For reference I also have the package versions here: http://i.imgur.com/mQ65r2v.png

Thanks very much for any help figuring this out :)

**Comment by dotansimha** [comment]
Hi @alecperkey 
Justed tried it with your fork.
You actual error is that your HTML files are not loaded correctly - if you try to access the HTML of the login page in this URL:
http://localhost:3000/packages/material-accounts/views/login.ng.html

You'll see the you are redirected to the main page. 
This is the same behavior that happens when you try to load it as AngularJS template - you get the main page...

The root of the mistake is the name of your package - Meteor uses your actual package name from your `package.js` and NOT your directory name under `packages/`. 
Also, Meteor replaces `:` character with `_`, so the actual URL of the template should be:
http://localhost:3000/packages/perk_material-accounts/views/login.ng.html

**Comment by alecperkey** [comment]
Awesome! Thanks, it works now! :+1:
